### ISSUE TITLE
sprintf() is missing an argument

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [IAMconsortium/iamc#13]
https://github.com/IAMconsortium/iamc/blob/c7e075c91ed58c06ca2ecd26e56c133e1a3b6497/R/RenameAndAggregate.R#L175

**Comment by tscheypidi** [comment]
fixed in https://github.com/IAMconsortium/iamc/commit/1d39cc4f81b102d02d44c4173518ab0bfa9f6574
